name: Instagram Reels Downloader Bot

on:
  schedule:
    # Runs every hour at 0 minutes past the hour
    # For example, at 00:00, 01:00, 02:00 UTC, etc.
    # You can adjust this cron schedule as needed.
    # To run manually, you can also trigger a 'workflow_dispatch' event.
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or any other suitable Python version like 3.10, 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Instagram Reels Downloader Bot
      env:
        # These are your secrets. You MUST set them in your GitHub repository settings.
        # Go to your repository -> Settings -> Secrets and variables -> Actions -> New repository secret
        INSTAGRAM_SESSION_ID: ${{ secrets.INSTAGRAM_SESSION_ID }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python main.py

    - name: Commit and push downloaded reels and log
      # This step will commit any new reels and the updated log file back to your repository.
      # This requires a PAT with 'repo' scope or default GITHUB_TOKEN permissions.
      # The default GITHUB_TOKEN usually has enough permissions for commits within the same repo.
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reels/
        # Check if there are any changes to commit
        git diff --quiet --exit-code || git commit -m "Automated: Downloaded new Instagram Reels"
        git push
      # If you encounter permission issues with git push, you might need to use a PAT
      # with 'repo' scope and configure it like this:
      # uses: ad-m/github-push-action@master
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
      #   branch: master # Or your main branch name

