# .github/workflows/run_bot.yml
name: Instagram Reels Bot

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  push:
    branches:
      - main

jobs:
  run_bot:
    runs-on: ubuntu-latest
    env:
      INSTAGRAM_SESSION_ID: ${{ secrets.INSTAGRAM_SESSION_ID }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run bot script
        run: python main.py
        # The INSTAGRAM_SESSION_ID and GEMINI_API_KEY are loaded from secrets
        # Make sure these secrets are set in the repository settings
